version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch
    ports:
      - 9200:9200
    networks:
      - usmart_default
  app:
    container_name: usmart
    build: .
    ports:
      - 8081:8081
    links:
      - elasticsearch:elasticsearch
    networks:
      - usmart_default
networks:
  usmart_default: